name: Run ZAP Proxy

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main

jobs:
  run-zap:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build ZAP Docker image
        run: docker build -t zap-custom .

      - name: Run ZAP container
        run: docker run -d -p 9090:9090 --name zap-container zap-custom

      - name: Wait for ZAP to initialize
        run: sleep 60 # Adjust this sleep time based on how long ZAP takes to start

      - name: Fetch ZAP logs
        run: docker logs zap-container
